version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: reddit_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reddit_db}
      POSTGRES_USER: ${POSTGRES_USER:-reddit_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-reddit_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - reddit_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-reddit_user} -d ${POSTGRES_DB:-reddit_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (optional - DB管理用)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: reddit_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - reddit_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  # Redis (将来のキャッシュ用)
  redis:
    image: redis:7-alpine
    container_name: reddit_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - reddit_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  reddit_network:
    driver: bridge
