services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: reddit_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reddit_db}
      POSTGRES_USER: ${POSTGRES_USER:-reddit_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-reddit_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
